databases:
  - name: minire-db
    databaseName: minire-db
    user: minire_db_user
    region: singapore

services:
  - type: web
    name: MiniRe
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: minire-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

